### PR TITLE
Use correct Imgix resize setting for "fit"

### PR DESCRIPTION
**Pull request by codyjames**
This is currently incorrectly using "clamp" which looks bizarre.

Imgix docs: https://docs.imgix.com/apis/url/size/fit

### CODE REVIEW

**Comment by codyjames** [comment]
This would resolve: https://github.com/nystudio107/craft-imageoptimize/issues/167

**Comment by khalwat** [comment]
Oh wow, sorry, I just did this independently. I really appreciate the PR tho!

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-imageoptimize-imgix/releases/tag/1.1.1

**Comment by codyjames** [comment]
@khalwat Great thanks!

**Pull request closed without merging**
